locale: en_us
features:
  leash:
    enabled: true
    pull-sound: minecraft:item.lead.untied
    pull-radius: 5
    pull-power: 2
    max-radius: 15
    show-particles: true
    play-sound: true
  pat:
    enabled: true
    particle: HEART
    allow-mobs: true
  gifts:
    enabled: true
    add-lore: true
    tnt:
      ignite: true # set false to disable tnt explosion
      accumulate: false # bigger explosion with each tnt
      instant: true
      power: 4 # works only if instant == true
      break-blocks: true
      cause-fire: false